import {
    // NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, GENERALMANAGER, MANAGER } from '@/constants/roles.constant'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        role: [],
        authority: [ADMIN, MANAGER],
        subMenu: [],
    },
    // {
    //     key: 'services',
    //     path: '/services/dealership',
    //     title: 'Services',
    //     translateKey: 'services',
    //     // translateKey: 'nav.services',
    //     icon: 'services',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     role: [],
    //     authority: [ADMIN],
    //     subMenu: [],
    // },
    // {
    //     key: 'vehicles',
    //     path: '/vehicles/in_shop',
    //     title: 'Vehicle Details',
    //     translateKey: 'vehicles',
    //     // translateKey: 'nav.vehicles',
    //     icon: 'vehicles',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     role: [],
    //     authority: [ADMIN, MANAGER, GENERALMANAGER],
    //     subMenu: [],
    // },
    // {
    //     key: 'jobsqueue',
    //     path: `/jobs/entries`,
    //     title: 'Jobs & Queue',
    //     translateKey: 'jobsqueue',
    //     icon: 'jobsqueue',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     role: [],
    //     authority: [ADMIN, MANAGER],
    //     subMenu: [],
    // },
    // {
    //     key: 'jobsqueue',
    //     path: '',
    //     title: 'Jobs & Queue',
    //     translateKey: 'nav.jobsqueue',
    //     icon: 'jobsqueue',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     role: [],
    //     authority: [ADMIN, MANAGER],
    //     subMenu: [
    //         {
    //             key: 'vehicles.details',
    //             path: `/vehicles/in_shop`,
    //             title: 'Vehicle Details',
    //             translateKey: 'nav.vehicles.details',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             role: [],
    //             authority: [ADMIN, MANAGER],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'jobsqueue.onpremise',
    //             path: `/on-premise-vehicles`,
    //             title: 'On-Premise',
    //             translateKey: 'nav.jobsqueue.onpremise',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             role: [],
    //             authority: [ADMIN, MANAGER],
    //             subMenu: [],
    //         }
    //     ],
    // },
    // {
    //     key: 'warranty',
    //     path: '/warranty',
    //     title: 'Warranty Work',
    //     translateKey: 'warranty',
    //     icon: 'warranty',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     role: [],
    //     authority: [ADMIN, MANAGER, GENERALMANAGER],
    //     subMenu: [],
    // },
    {
        key: 'account',
        path: '',
        title: 'Account',
        translateKey: 'nav.account.account',
        icon: 'account',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, MANAGER],
        role: [],
        subMenu: [
            {
                key: 'account.settings',
                path: `account/settings/password`,
                title: 'Settings',
                translateKey: 'nav.account.settings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                role: [],
                authority: [ADMIN, MANAGER],
                subMenu: [],
            },
            // {
            //     key: 'account.activityLog',
            //     path: `account/activity-log`,
            //     title: 'Activity Log',
            //     translateKey: 'nav.account.activityLog',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     role: [],
            //     authority: [ADMIN, MANAGER],
            //     subMenu: [],
            // },
        ],
    },
    // {
    //     key: 'customers',
    //     path: '',
    //     title: 'Manage Customers',
    //     translateKey: 'nav.customers.customers',
    //     icon: 'customers',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     role: [],
    //     authority: [ADMIN, MANAGER],
    //     subMenu: [
    //         {
    //             key: 'customers.customerList',
    //             path: `/customers`,
    //             title: 'Customers',
    //             translateKey: 'nav.customers.customerList',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             role: [],
    //             authority: [ADMIN, MANAGER],
    //             subMenu: [],
    //         },
    //         // {
    //         //     key: 'customers.customerDetail',
    //         //     path: `/customers/customer-details/12`,
    //         //     title: 'Customer Details',
    //         //     translateKey: 'nav.customers.customerDetail',
    //         //     icon: '',
    //         //     type: NAV_ITEM_TYPE_ITEM,
    //         //     role: [],
    //         //     authority: [ADMIN, MANAGER],
    //         //     subMenu: [],
    //         // },
    //     ],
    // },
    // {
    //     key: 'invoice',
    //     path: '',
    //     title: 'Manage Invoice',
    //     translateKey: 'nav.invoice.invoice',
    //     icon: 'invoice',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     role: [],
    //     authority: [ADMIN, MANAGER],
    //     subMenu: [
    //         {
    //             key: 'invoice',
    //             path: `/invoice`,
    //             title: 'Invoice',
    //             translateKey: 'nav.invoice',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             role: [],
    //             authority: [ADMIN, MANAGER],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'invoice.sent',
    //             path: `/sent-out-invoice`,
    //             title: 'Invoice Sent',
    //             translateKey: 'nav.invoice.invoice.sent',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             role: [],
    //             authority: [ADMIN, MANAGER],
    //             subMenu: [],
    //         },
    //         // {
    //         //     key: 'invoice.invoiceDetail',
    //         //     path: `/invoice/123`,
    //         //     title: 'Invoice Details',
    //         //     translateKey: 'nav.invoice.invoiceDetail',
    //         //     icon: '',
    //         //     type: NAV_ITEM_TYPE_ITEM,
    //         //     role: [],
    //         //     authority: [ADMIN, MANAGER],
    //         //     subMenu: [],
    //         // },
    //     ],
    // },

    {
        key: 'groupMenu.collapse',
        path: '',
        title: 'Manage Employees',
        translateKey: 'nav.groupMenu.collapse.manage',
        icon: 'manage',
        type: NAV_ITEM_TYPE_COLLAPSE,
        role: [],
        authority: [ADMIN, MANAGER],
        subMenu: [
            {
                key: 'staff',
                path: '/staff/all_staff',
                title: 'Staff',
                translateKey: 'nav.groupMenu.collapse.manage.staff',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                role: [],
                authority: [ADMIN, MANAGER],
                subMenu: [],
            },
            {
                key: 'managers',
                path: '/managers',
                title: 'Managers',
                translateKey: 'nav.groupMenu.collapse.manage.managers',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                role: [],
                authority: [ADMIN, MANAGER],
                subMenu: [],
            },
            // {
            //     key: 'genmanagers',
            //     path: '/general-managers',
            //     title: 'General Managers',
            //     translateKey: 'nav.groupMenu.collapse.manage.genmanagers',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     role: [],
            //     authority: [ADMIN, MANAGER, GENERALMANAGER],
            //     subMenu: [],
            // },
            // {
            //     key: 'departments',
            //     path: '/departments',
            //     title: 'Departments',
            //     translateKey: 'nav.groupMenu.collapse.manage.departments',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     role: [],
            //     authority: [ADMIN, MANAGER],
            //     subMenu: [],
            // },
        ],
    },
    // {
    //     key: 'inventory',
    //     path: '/inventory',
    //     title: 'Inventory',
    //     translateKey: 'inventory',
    //     icon: 'inventory',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     role: [],
    //     authority: [ADMIN, MANAGER, GENERALMANAGER],
    //     subMenu: [],
    // },
    // {
    //     key: 'messaging',
    //     path: '/messaging',
    //     title: 'Messaging',
    //     translateKey: 'messaging',
    //     icon: 'messaging',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     role: [],
    //     authority: [ADMIN, MANAGER, GENERALMANAGER],
    //     subMenu: [],
    // },
]

export default navigationConfig
